version: '3'
services:

  web:
    build: ./web
    image: akscontainerregistry.azurecr.io/proxy-web

  auth:
    build: ./auth
    image: akscontainerregistry.azurecr.io/proxy-auth
    ports:
      - 7000:80
