version: '3'
services:

  web:
    build: ./web
    image: ryannhg/nginx-web

  auth:
    build: ./auth
    image: ryannhg/nginx-auth
    ports:
      - 7000:80
    volumes:
      - shared:/etc/shared
    depends_on:
      - passgen

  passgen:
    image: httpd
    volumes:
      - shared:/etc/shared
    command: htpasswd -bc /etc/shared/.htpasswd username password

volumes:
  shared:
